<?php
/**
 * Created by PhpStorm.
 * User: joels
 * Date: 21/04/2017
 * Time: 12:49 PM
 */

namespace enigmatix\flexSlider;


use yii\base\Widget;
use yii\bootstrap\Html;



class FlexSlider extends Widget
{

    public $items = [];

    public $item;

    public function init() {

        parent::init(); // TODO: Change the autogenerated stub

        $this->view->registerAssetBundle(FlexSliderAsset::className());

    }

    public function run() {

        $this->view->registerJs('$("#' . $this->id . '").flexslider({controlNav: "thumbnails"})');

        return Html::tag('div',$this->slides,['id' => $this->id, 'class' => 'col-sm-12 flexslider']);
    }

    public function getSlides() {

        if($this->item === null){
            $item = function($item, $index){
                return Html::tag('li', Html::img($item->getViewLink()), ['data-thumb' => $item->getViewLink()]);
            };
        } else {
            $item = $this->item;
        }

        return Html::ul($this->items, ['class' => 'slides', 'item' => $item]);
    }
}